version: '3.9'
networks:
  server:
    external: true
  hackrbot:
    driver: bridge
services:
  hackrbothackrlabs:
    container_name: hackrbothackrlabs
    restart: always
    networks:
      server:
        aliases:
          - hackrbothackrlabs
      hackrbot:
        aliases:
          - web
    build: 
      context: ./web
      args:
        - PORT=${PORT}
        - NPM_TOKEN=${NPM_TOKEN}
    env_file:
      - .env
    volumes:
      - ./web:/usr/local/share/hackrbot.hackrlabs.dev
      - ./web/public/static:/usr/local/share/hackrbot.hackrlabs.dev/public/static
    depends_on:
      - dbhackrbothackrlabs
  dbhackrbothackrlabs:
    container_name: dbhackrbothackrlabs
    image: postgres
    restart: always
    networks:
      hackrbot:
        aliases:
          - db
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
  bothackrbothackrlabs:
    container_name: bothackrbothackrlabs
    restart: always
    depends_on:
      - hackrbothackrlabs
    networks:
      hackrbot:
        aliases:
          - bot
    build:
      context: ./bot
      args:
        - PORT=${PORT}
    env_file:
      - .env
    volumes:
      - ./bot:/usr/local/share/bot.hackrbot.hackrlabs.dev
      - /usr/local/share/bot.hackrbot.hackrlabs.dev/dist