import { useEffect, useState } from 'react';
import Head from 'next/head'
import { useSession } from "next-auth/react";
import { Container } from '@mui/system';
import { Autocomplete, Box, Button, FormControl, Grid, InputLabel, MenuItem, OutlinedInput, Paper, Select, TextField, Typography } from '@mui/material';

import { FaIcon } from '@/components/FaIcon';
import { faArrowRight } from '@fortawesome/sharp-solid-svg-icons';
import axios from 'axios';
import { Command } from '@/models/Command';

export default function Home() {
  const { data: session } = useSession()
  const [commands, setCommands] = useState<Command[]>([])

  const getCommands = async () => {
    const { data } = await axios.get<Command[]>("/api/commands")
    return data
  }

  useEffect(() => {
    getCommands().then((data) => {
      setCommands(data)
    })
  }, [])

  return (
    <>
      <Head>
        <title>hackrbot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          {
            session
              ? <>
                <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
                  <Paper sx={{ p: 4, display: 'flex', flexDirection: 'column', alignItems: 'center' }} elevation={24}>
                    <Typography variant='h3'>Great to have you here, {session.user.name}! 👋🏽</Typography>
                    <Typography variant='h5'>To get started, select one of the servers from the sidebar!</Typography>
                    <Typography variant='subtitle1'>If you don&apos;t see a server there, hackrbot isn&apos;t available for your server just yet.</Typography>
                    <Typography variant='subtitle1'>hackrbot is a bot dedicated to hackr&apos;s servers only. If you know him, reach out!</Typography>
                  </Paper>
                </Box>
              </>
              : <>
                <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
                  <Paper sx={{ p: 4, display: 'flex', flexDirection: 'column', alignItems: 'center' }} elevation={24}>
                    <Typography variant='h3'>Welcome to hackrbot!</Typography>
                    <Typography variant='h5'>Please sign in to continue.</Typography>
                  </Paper>
                </Box>
              </>
          }
        </Container>
      </main>
    </>
  )
}
