name: Pre-PR Checks
on:
  pull_request:
    branches:
      - main
      - 'release/**'
jobs:
  Generate-Env-File-And-Run-Docker-Compose:
    runs-on: ubuntu-22.04
    environment: prod
    env:
      PORT: ${{ vars.PORT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      HACKRBOT_TOKEN: ${{ secrets.HACKRBOT_TOKEN }}
      DISCORD_CLIENT_ID: ${{ vars.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      HACKRBOT_DB_URL: ${{ secrets.HACKRBOT_DB_URL }}
      NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: generate env file
        run: |
          echo "PORT=${PORT}" >> .env;
          echo "NPM_TOKEN=${NPM_TOKEN}" >> .env;
          echo "HACKRBOT_TOKEN=${HACKRBOT_TOKEN}" >> .env;
          echo "DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}" >> .env;
          echo "DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}" >> .env;
          echo "JWT_SECRET=${JWT_SECRET}" >> .env;
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env;
          echo "HACKRBOT_DB_URL=${HACKRBOT_DB_URL}" >> .env;
          echo "NEXTAUTH_URL=${NEXTAUTH_URL}" >> .env;
      - name: tmate session
        uses: mxschmitt/action-tmate@v3
      - name: docker compose build
        run: |
          docker-compose build